export const questions = [
  {
    id: 1,
    question:
      "If you haven’t done so yet, finish the exercises from the previous lab.",
    answer: "This is the answer",
    database: 2,
    startingText: "None",
    response: "This has been a response",
    respondAfter: 3,
    autoResponse: false,
    completed: true,
  },
  {
    id: 2,
    question: "Display the name of each employee with his department name.",
    answer: "This is the answer",
    database: 2,
    startingText: "None",
    response: "This has been a response",
    respondAfter: 3,
    autoResponse: false,
    completed: false,
  },
  {
    id: 3,
    question:
      "Display a list of ALL departments with their employees (i.e. list a department even if it hasn’t got any employees).",
    answer: "This is the answer",
    database: 2,
    startingText: "None",
    response: "This has been a response",
    respondAfter: 3,
    autoResponse: false,
    completed: false,
  },
  {
    id: 4,
    question: "Display the department names with the names of their managers.",
    answer: "This is the answer",
    database: 2,
    startingText: "None",
    response: "This has been a response",
    respondAfter: 3,
    autoResponse: false,
    completed: false,
  },
  {
    id: 5,
    question:
      "Display the names of each employee with the name of his/her boss.",
    answer: "This is the answer",
    database: 2,
    startingText: "None",
    response: "This has been a response",
    respondAfter: 3,
    autoResponse: false,
    completed: false,
  },
  {
    id: 6,
    question:
      "Display the names of each employee with the name of his/her boss with a blank for the boss of the president.",
    answer: "This is the answer",
    database: 2,
    startingText: "None",
    response: "This has been a response",
    respondAfter: 3,
    autoResponse: false,
    completed: false,
  },
  {
    id: 7,
    question:
      "Display the employee number and name of each employee who manages other employees with the number of people he or she manages.",
    answer: "This is the answer",
    database: 2,
    startingText: "None",
    response: "This has been a response",
    respondAfter: 3,
    autoResponse: false,
    completed: false,
  },
  {
    id: 8,
    question:
      "Repeat the display for the last question, but this time display the rows in descending order of the number of employees managed.",
    answer: "This is the answer",
    database: 1,
    startingText: "None",
    response: "This has been a response",
    respondAfter: 3,
    autoResponse: false,
    completed: false,
  },
]
